{
 "title": "RealTimeTrafficMonitoringDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Real Time Network Throughput",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 10, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "query": "from(bucket: \"network_stats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network_summary\" and r._field == \"bandwidth_mbps\")"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "gauge",
   "gridPos": { "x": 10, "y": 0, "w": 3, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"network_stats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network_summary\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bandwidth_mbps\")\r\n  |> last()\r\n  |> yield(name: \"bant_genisligi\")"
    }
   ]
  },
  {
   "title": "ProtocolDistribution",
   "type": "piechart",
   "gridPos": { "x": 13, "y": 0, "w": 4, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"network_stats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network_traffic\")\r\n  |> filter(fn: (r) => r._field == \"bytes\")\r\n  |> group(columns: [\"protocol\"])\r\n  |> sum()"
    }
   ]
  },
  {
   "title": "Network Latency",
   "type": "timeseries",
   "gridPos": { "x": 17, "y": 0, "w": 7, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"network_stats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network_health\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rtt_ms\")"
    }
   ]
  },
  {
   "title": "PPS",
   "type": "gauge",
   "gridPos": { "x": 10, "y": 4, "w": 3, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"network_stats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network_summary\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_per_second\")\r\n  |> last()\r\n  |> yield(name: \"bant_genisligi\")"
    }
   ]
  },
  {
   "title": "Signal Strength (Dbm)",
   "type": "bargauge",
   "gridPos": { "x": 13, "y": 6, "w": 11, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"network_stats\") \r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network_wifi\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"signal_dbm\")  // <-- Burası değişti\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Service Distribution",
   "type": "bargauge",
   "gridPos": { "x": 0, "y": 7, "w": 10, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"network_stats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network_traffic\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes\")\r\n  |> group(columns: [\"service\"])\r\n  |> sum()\r\n  |> sort(columns: [\"_value\"], desc: true) // YENİ: En çoktan en aza sırala!"
    }
   ]
  },
  {
   "title": "Throughput (Last 5 Seconds)",
   "type": "stat",
   "gridPos": { "x": 10, "y": 8, "w": 3, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"network_stats\")\r\n  |> range(start: -5s)\r\n  |> filter(fn: (r) => r._measurement == \"network_summary\" and r._field == \"bandwidth_mbps\")\r\n  |> filter(fn: (r) => r._value > 0.0)\r\n  |> mean()"
    }
   ]
  },
  {
   "title": "Service Distribution",
   "type": "piechart",
   "gridPos": { "x": 13, "y": 9, "w": 4, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"network_stats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network_traffic\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes\")\r\n  |> group(columns: [\"service\"])\r\n  |> sum()\r\n  |> yield(name: \"toplam_veri\")"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "x": 17, "y": 9, "w": 7, "h": 7 },
   "targets": [
    {
     "query": "from(bucket: \"network_stats\") \r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network_health\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"packet_loss\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"paket_kaybi\")"
    }
   ]
  },
  {
   "title": "Mean Packet Count ",
   "type": "stat",
   "gridPos": { "x": 10, "y": 11, "w": 3, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "p" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"network_stats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network_summary\" and r._field == \"packets_per_second\")\r\n  |> mean()"
    }
   ]
  },
  {
   "title": "Top Talkers",
   "type": "bargauge",
   "gridPos": { "x": 0, "y": 14, "w": 13, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"network_stats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network_traffic\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes\")\r\n  |> group(columns: [\"dest_ip\", \"dst_port\", \"service\"])\r\n  |> sum()\r\n  |> top(n: 10, columns: [\"_value\"])\r\n  |> yield(name: \"top_talkers\")"
    }
   ]
  },
  {
   "title": "Inbound / Outbound Traffic",
   "type": "timeseries",
   "gridPos": { "x": 13, "y": 16, "w": 11, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"network_stats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network_traffic\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes\")\r\n  |> filter(fn: (r) => r[\"source_ip\"] =~ /^192\\.168\\.|^10\\.|^172\\./)\r\n  |> group()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"Upload\")"
    },
    {
     "query": "from(bucket: \"network_stats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network_traffic\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes\")\r\n  |> filter(fn: (r) => r[\"dest_ip\"] =~ /^192\\.168\\.|^10\\.|^172\\./)\r\n  |> group()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"Download\")"
    }
   ]
  },
  {
   "title": "Total Traffic and IP's",
   "type": "table",
   "gridPos": { "x": 0, "y": 22, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"network_stats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network_traffic\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes\")\r\n  |> group(columns: [\"source_ip\", \"dest_ip\"]) // Kim kiminle konuşuyor ayır\r\n  |> sum() // Toplam sömürdükleri veriyi hesapla\r\n  |> group() // Sıralama yapabilmek için tabloyu tek parça yap\r\n  |> sort(columns: [\"_value\"], desc: true) // En çoktan en aza sırala\r\n  |> limit(n: 10) // Sadece en çok veri yiyen ilk 10 kişiyi göster"
    }
   ]
  },
  {
   "title": "Network Packet Geolocation Radar",
   "type": "geomap",
   "gridPos": { "x": 12, "y": 22, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"network_stats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network_traffic\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes\" or r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> pivot(rowKey:[\"_time\", \"dest_ip\", \"service\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => exists r.latitude and exists r.longitude and exists r.bytes)\r\n  |> group() \r\n  |> keep(columns: [\"_time\", \"dest_ip\", \"service\", \"latitude\", \"longitude\", \"bytes\"])"
    }
   ]
  }
 ]
}